version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always
    networks:
      - spring-postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "db_prod" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

  backend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
          JAR_FILE: /target/*.jar
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
        - react-spring
        - spring-postgres
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    networks:
      - react-spring
    depends_on:
      - backend
    environment:
      VITE_API_URL: ${API_URL}
    expose:
      - 80

volumes:
  postgres-data: {}

networks:
  react-spring: {}
  spring-postgres: {}